use std::collections::VecDeque;

fn program(mut input: VecDeque<i128>) {
    let (mut w, mut x, mut y, mut z) = (0, 0, 0, 0);
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 11;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 16;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 12;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 11;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 13;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 12;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -5;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 12;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -3;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 12;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 14;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 2;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 15;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 11;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -16;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 4;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 14;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 12;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 1;
    x += 15;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 9;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -7;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 10;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -11;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 11;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -6;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 6;
    y *= x;
    z += y;
    w = input.pop_front().unwrap();
    x = 0;
    x += z;
    x %= 26;
    z /= 26;
    x += -11;
    x = if x == w { 1 } else { 0 };
    x = if x == 0 { 1 } else { 0 };
    y = 0;
    y += 25;
    y *= x;
    y += 1;
    z *= y;
    y = 0;
    y += w;
    y += 15;
    y *= x;
    z += y;
}
